### ISSUE TITLE
What is Custom Language Properties doing? 

### ISSUE THREAD

**Issue by schittli** [ArturoDent/custom-comments#2]
Hello

**thank you very much for sharing your very interesting work!,**

Unfortunately, it is not clear what exactly this extension changes, maybe it's my understanding of the English language.

What is Custom Language Properties doing?

1. Does it just change how comments are displayed and the source code files remain unchanged?
2. Does it provide the ability to enter comments with other characters that are then converted to programming language strings?
3. Is it doing something else?

Thanks a lot for any light to the question 😄 
Kind regards, Thomas

**Comment by ArturoDent** [comment]
Hi,

This extension changes the source code - it can access the language configuration file for the language and change its line or blockComments.  There is an api exposed by vscode to do this.

The characters you enter for a comment replace whatever the default characters are for that language (at least as implemented by a language extension).  Sometimes that extension implementation is incorrect or you want to add something to the comment characters like `// ** ` instead of only the `//`.  

If it isn't a case of an incorrect language extension implementation I suggest being fairly cautious in how you change the comment characters - in case your code goes to someone else or another ide without this `Custom Language Properties` extension and setting.  SO I would start with the usual comment characters at the beginning and then add something if you want to the end.

You can also add to the brackets that are recognized by the language server, without any ill effects for other users - they just won't get the autocompletion for the new bracket types that you would get.
